FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -m tccuser
WORKDIR /app

COPY requerimentos.txt .
RUN pip install -r requerimentos.txt

COPY app.py .

RUN chown -R tccuser:tccuser /app
USER tccuser

EXPOSE 8080

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "2", "app:app"]
